defmodule GenesisPubSub.Message.Metadata do
  @moduledoc """
  A Message's metadata helps correlate information about how a message was
  created and the flow that it was created in. Metadata is helpful in
  debugging and infrastructure of pubsub. For storing any domain information the
  `Message` data field should be used. Consumers of events should very rarely
  need to write metadata directly.

  Fields:

  * `event_id` - unique identifier for event.
    This field is assigned at message creation time, it can be assigned
    manually or otherwise will be autogenerated.

  * `eventadapter_event_id_id` - unique identifier for event from the adapter.
    This field is assigned at publish time. Unpublished events will not contain
    this value.

  * `created_at` - UTC timestamp for when message was created

  * `published_at` - UTC timestamp for when message was published
    Also supllied at publish time.

  * `correlation_id` - id shared among events as part of a workflow
    As events are fired and responding to each other they all share the same
    `correlation_id`. Given this id you could retrieve all events that occured in
    a given action on the system.

  * `causation_id` - event id that caused this message to be created.
    When firing an event in response to consuming an event the previous event's
    `event_id` becomes the next events `causation_id`. Given all events by
    `correlation_id` they could be put in order by their `causation_id`. The
    first event having a nil `causation_id`.

  * `user` - user that kicked off this event stream.
    Supplied at message creation and copied on followed metadata.
    * `account_id` - id number of user account 
    * `bank_account_id` - id of bank account for user
    * `firebase_uid` - id of firebase auth id
    * `email` - user email
    * `id` - user id

  * `topic` - topic where message resides
    Supplied at publishing time by producer.

  * `schema` - schema information for how message can be encoded/decoded
    A `GenesisPubSub.SchemaSpec` struct supporting client side
    encoding/decoding. Assigned by Producer at publish time.

  * `service` - name of service or deployable responsible for dispatching event
    * Assigned by Producer at publish time.
  """
  alias GenesisPubSub.SchemaSpec

  defmodule User do
    @type t :: %__MODULE__{
            account_id: String.t() | nil,
            bank_account_id: String.t() | nil,
            firebase_uid: String.t() | nil,
            email: String.t() | nil,
            id: String.t() | nil
          }

    defstruct [:account_id, :bank_account_id, :firebase_uid, :email, :id]
  end

  defstruct [
    :event_id,
    :adapter_event_id,
    :created_at,
    :published_at,
    :correlation_id,
    :causation_id,
    :user,
    :topic,
    :schema,
    :service
  ]

  @type unpublished_t :: %__MODULE__{
          event_id: GenesisPubSub.uuid(),
          adapter_event_id: nil,
          created_at: DateTime.t(),
          correlation_id: GenesisPubSub.uuid(),
          causation_id: GenesisPubSub.uuid() | nil,
          published_at: nil,
          schema: SchemaSpec.t(),
          user: User.t(),
          service: String.t(),
          topic: String.t()
        }

  @type published_t :: %__MODULE__{
          event_id: GenesisPubSub.uuid(),
          adapter_event_id: any(),
          created_at: DateTime.t(),
          correlation_id: GenesisPubSub.uuid(),
          # first event of a workflow would have nil causation
          # all following events should have one
          causation_id: GenesisPubSub.uuid() | nil,
          published_at: DateTime.t(),
          schema: SchemaSpec.t(),
          service: String.t(),
          topic: String.t(),
          user: User.t()
        }

  @typedoc """
  Many pubsub systems don't support metadata that has any level of nesting. This
  type shows a message put into a flattened format as a plain map making it easy
  to serialize and publish through external systems.
  """
  @type encodable :: %{
          event_id: GenesisPubSub.uuid(),
          adapter_event_id: any(),
          created_at: String.t(),
          correlation_id: GenesisPubSub.uuid(),
          causation_id: GenesisPubSub.uuid() | nil,
          published_at: String.t(),
          service: String.t(),
          topic: String.t(),
          schema_type: String.t(),
          schema_encoder: String.t() | nil,
          user_id: String.t() | nil,
          user_account_id: String.t() | nil,
          user_bank_account_id: String.t() | nil,
          user_firebase_uid: String.t() | nil,
          user_email: String.t() | nil
        }

  @doc "Creates new `Metadata` with default values applied"
  def new(meta_data \\ %{}) do
    user = Map.get(meta_data, :user, %{})

    params =
      %{
        event_id: UUID.uuid4(),
        correlation_id: UUID.uuid4(),
        created_at: DateTime.utc_now(),
        causation_id: nil
      }
      |> Map.merge(meta_data)
      |> Map.put(:user, struct(__MODULE__.User, user))

    struct!(__MODULE__, params)
  end

  @doc """
  Generates a new `Metadata` by following a previous events metadata.

  Many of the fields of the metadata are correlated to the event that preceeded
  it. This function helps line up the wires so that fields are correctly correlated.
  """
  def follow(%__MODULE__{} = previous_metadata, meta_data \\ %{}) do
    # avoid copying other fields that are unique to previous metadata
    mergeable_meta_data = Map.drop(meta_data, [:created_at, :correlation_id, :causation_id])

    params =
      %{
        event_id: UUID.uuid4(),
        created_at: DateTime.utc_now(),
        correlation_id: previous_metadata.correlation_id,
        causation_id: previous_metadata.event_id,
        user: previous_metadata.user
      }
      |> Map.merge(mergeable_meta_data)

    struct!(__MODULE__, params)
  end

  @spec to_encodable(__MODULE__.published_t() | __MODULE__.unpublished_t()) :: encodable()
  @doc """
  Converts `metadata` into a serializable format.

  Most pubsub systems don't support nested maps in their metadata. This function
  ensures that a version of metadata exists that is completely flat and should
  be easily serializable with json.
  """
  def to_encodable(%__MODULE__{schema: %SchemaSpec{} = schema, user: user} = meta) do
    json_codec = GenesisPubSub.json_codec()
    # convert structs into encodable maps
    # this helps support more json protocols
    meta
    |> Map.from_struct()
    |> encode_schema(schema)
    |> Map.delete(:schema)
    |> encode_user(user)
    |> Map.delete(:user)
    # turn into json to stringify fields
    |> json_codec.encode!()
    # turn back into json map
    |> json_codec.decode!()
  end

  def encode(%__MODULE__{schema: nil} = meta) do
    json_codec = GenesisPubSub.json_codec()
    # convert structs into encodable maps
    # this helps support more json protocols
    meta
    |> Map.from_struct()
    |> Map.delete(:schema)
    # turn into json to stringify fields
    |> json_codec.encode!()
    # turn back into json map
    |> json_codec.decode!()
  end

  @spec from_encodable(encodable()) :: __MODULE__.published_t() | __MODULE__.published_t()
  @doc """
  Converts an encodable map into a `%Metadata{}`.
  """
  def from_encodable(encodable) do
    params =
      encodable
      # Ensure dates are DateTime and not string
      |> Map.update("created_at", nil, fn
        %DateTime{} = created_at ->
          created_at

        created_at when is_binary(created_at) ->
          {:ok, created_at, _offset} = DateTime.from_iso8601(created_at)
          created_at
      end)
      |> Map.update("published_at", nil, fn
        %DateTime{} = published_at ->
          published_at

        published_at when is_binary(published_at) ->
          {:ok, published_at, _offset} = DateTime.from_iso8601(published_at)
          published_at
      end)
      # deserialze schema fields into a spec
      |> case do
        %{"schema_type" => "proto", "schema_encoder" => encoder} = params ->
          Map.put(params, "schema", SchemaSpec.proto(String.to_atom(encoder)))

        %{"schema_type" => "json"} = params ->
          Map.put(params, "schema", SchemaSpec.json())
      end
      |> Map.put(
        "user",
        struct(User, %{
          id: encodable["user_id"],
          account_id: encodable["user_account_id"],
          bank_account_id: encodable["user_bank_account_id"],
          firebase_uid: encodable["user_firebase_uid"],
          email: encodable["user_email"]
        })
      )
      |> Map.take([
        "event_id",
        "adapter_event_id",
        "created_at",
        "published_at",
        "correlation_id",
        "causation_id",
        "user",
        "topic",
        "service",
        "schema"
      ])
      # Convert keys to atoms
      |> Enum.map(fn {key, value} -> {String.to_existing_atom(key), value} end)

    struct!(__MODULE__, params)
  end

  # serialized metadata needs to be a map of flat keys
  # turn schema into a flattened representation
  defp encode_schema(serialized_metadata_params, %SchemaSpec{type: :json}) do
    Map.put(serialized_metadata_params, :schema_type, :json)
  end

  defp encode_schema(serialized_metadata_params, %SchemaSpec{type: :proto, properties: %{encoder: encoder}}) do
    serialized_metadata_params
    |> Map.put(:schema_type, :proto)
    |> Map.put(:schema_encoder, encoder)
  end

  defp encode_user(serialized_metadata_params, %User{} = user) do
    serialized_metadata_params
    |> Map.put(:user_id, user.id)
    |> Map.put(:user_account_id, user.account_id)
    |> Map.put(:user_bank_account_id, user.bank_account_id)
    |> Map.put(:user_firebase_uid, user.firebase_uid)
    |> Map.put(:user_email, user.email)
  end
end
